---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_system }}, the Version is {{ ansible_net_version}}"

    - name: Run ping
      ios_ping:
        dest: 192.168.90.250

  vars:
    ansible_network_os: ios
